[package]
name = "tracegit"
version = "0.2.0"
edition = "2024"

[dependencies]
git2 = "0.18.1"
clap = { version = "4.4.6", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.0"
anyhow = "1.0.75"
